### ISSUE TITLE
Allow user to upload custom fonts

### ISSUE THREAD

**Issue by AmenJlili** [basshelal/Wudooh#5] opened 2019-06-09 18:55 UTC
Allow user to add custom fonts.

**Comment by basshelal** [comment] 2019-06-09 19:10
@jliliamen [Yes this is already planned!](https://github.com/basshelal/Wudooh#future-features).
We'd probably need to enforce that the user uploads woff2 font files.
This is tricky but I would like this and I know others would too.

**Comment by basshelal** [comment] 2019-08-13 05:06
Update after some research into the subject:

This is *very* tricky and even if implemented correctly, would still not be perfect.

Chrome has a strict 100kb limit on `chrome.storage.sync` (firefox too) `.woff2` files are anywhere between 30kb to 120kb, so this won't work.

If we go the other route of just uploading files to the extension's local directory there is no guarantee on that. Chrome may delete anything however it sees fit when an update of any kind occurs, and this too would not be cross-browser.

The only maybe feasible option is to use `chrome.storage.local` which has a 5MB limit that you could increase to be unlimited but this won't be cross browser so if the user does upload custom fonts, they will only exist on their local browser and not across browsers, which is really not ideal. The other major problem with that approach is that we'd need to *somehow* add the `css` `@font-face` information of the newly uploaded font(s) to `styles.css` in order to be used, that would be difficult to do programmatically. 

I won't close this idea just yet because maybe I'll discover something that would make this easier, but it seems that this is much more difficult than I thought and it's likely this feature won't be implemented unfortunately.

**Comment by AmenJlili** [comment] 2019-08-13 13:54
How about you using the Windows fonts? Put the burden of storage onto the OS. There should be a JS API that lets access Windows fonts. I don't know about OS and Linux.

**Comment by basshelal** [comment] 2019-08-13 18:45
@jliliamen That sounds like a decent idea, I'll look into it. But this means the user will *"upload"* fonts by installing them on their machine first and then telling the extension which installed font to use. It''s not optimal (optimal seems to be impossible at this point) but it's worth the try.

**Comment by basshelal** [comment] 2020-02-24 01:06
@jliliamen You absolute legend! Your trick works with some css and js trickery!
I'm documenting it all here for myself later.

If the user wants to use a custom font they will first have to download and install that font on their local machine. The supported font types I believe are: 
* otf
*  ttf
*  woff and woff2
After they've installed the font they'll need to open Wudooh and open the "Custom Fonts" helper page.
This helper page is a separate page that will contain the necessary shit needed to manage your custom fonts, such as viewing, adding and deleting (CRUDs).

**Important note on storage!**
The only thing we will store is the font's name on the machine as a `string`, not the font itself and this will only be saved on `chrome.storage.local` NOT `sync`. The reason for this is that custom fonts will be machine dependent and so if the user has Wudooh installed on Chrome in his Mac and his other Windows machine, likely they won't have the same installed fonts and so there will be errors. The fonts should thus be a local item. We need to detail all of this on the page to make sure users understand this.

Users add the font to the custom fonts by typing in the name of the font family precisely as it is named on the machine's font page. This could ignore stylings and weights like Bold, Italic, Mono and would simply the font's family name like `Roboto` but could also include those as long as it is installed on the machine like that.

How this then works is we add a css `@font-face` style element to the DOM and specify the `src: local` and it just works 😝!

Users can edit that name, or delete it in the new Custom Fonts helper page but the key thing is that it's all local, no cross device cross browser crap. 

We also need to make sure we have validations and error handling if possible such as when the font is not found, although that part looks much harder, I'm not too sure about this part.

There's a bit more to this, it's not an easy feature by any means simply because of the many edge cases but I have now confirmed that not only is it possible but it actually works!

Not sure if we should put this on the next update or not, I'll see about that later.

**Comment by AmenJlili** [comment] 2020-03-08 01:05
@basshelal  No you are the legend! Thanks for your hard work!

**Comment by basshelal** [comment] 2020-03-08 23:27
This hasn't fully been done yet so I'm reopening it so that I know what needs to be done when I have time to work on this again!

**Comment by basshelal** [comment] 2020-04-08 23:17
**HUGE IMPROVEMENT!**
Because we are just injecting CSS for each Custom Font, we can now...

**ADD FONTS HOSTED ONLINE WITHOUT INSTALLING THEM!**

A Custom Font is made up of:
* A name: the one on the machine (needs to be exact) or anything if it's not installed
* A display name: Just how you want to see it called on the extension, optional, defaults to the main name
* URL: Optional url location of the font, this needs to end in a font extension like .woff2, .ttf etc. Essentially the location of font on the web.

So the extension basically injects a CSS `@font-face` where necessary for every Custom Font stored in `storage.sync`.

The CSS is:
``` CSS
@font-face {
    font-family: '${fontName}';
    src: local('${fontName}'), url('${fontUrl}');
}
```

It will always try to fetch the font locally before going to the web.

I'll need to write some help guides for user's to know how to use it.

I'll also see about maybe adding or modifying some aspects but the fact that this works perfectly (and is relatively easy) is super exciting 😆😆😆!

**Comment by basshelal** [comment] 2020-05-05 04:58
This is done but in a *Beta* version.

This is because it's quite complex and I'd like to see some user feedback and use cases from it as well as iron out the details later myself after my own personal use away from the development environment.

It's a difficult feature to say the least. Making it work is ok, but making it work in the edge cases is tricky, especially without proper automated testing, which I will now have to do in the next update or so to ensure the codebase is sturdy and can live long which it now will. We're nearly at 800 users, this is kind of a big deal now.

But overall I'd say I'm 90% confident with the current state of it, hence the *Beta* tag.

I'll remove it from *Beta* in a future update hopefully.

Closing (finally 😁)

**Closed as completed by basshelal** 2020-05-05 04:58 UTC
Labels: New feature
